"""Common tech skills for local resume/job matching (no API)."""

SKILLS: tuple[str, ...] = (
    "python",
    "java",
    "javascript",
    "typescript",
    "c++",
    "c#",
    "go",
    "golang",
    "rust",
    "ruby",
    "php",
    "swift",
    "kotlin",
    "scala",
    "r",
    "matlab",
    "sql",
    "html",
    "css",
    "react",
    "reactjs",
    "vue",
    "vuejs",
    "angular",
    "next.js",
    "nextjs",
    "node.js",
    "nodejs",
    "express",
    "django",
    "flask",
    "fastapi",
    "spring",
    "spring boot",
    "laravel",
    "rails",
    ".net",
    "asp.net",
    "flutter",
    "dart",
    "android",
    "ios",
    "pyqt",
    "pyqt5",
    "tkinter",
    "selenium",
    "playwright",
    "puppeteer",
    "pytest",
    "unittest",
    "jest",
    "cypress",
    "docker",
    "kubernetes",
    "aws",
    "azure",
    "gcp",
    "terraform",
    "ansible",
    "jenkins",
    "github actions",
    "ci/cd",
    "git",
    "linux",
    "bash",
    "powershell",
    "rest",
    "rest api",
    "graphql",
    "grpc",
    "microservices",
    "api",
    "mongodb",
    "postgresql",
    "postgres",
    "mysql",
    "redis",
    "elasticsearch",
    "sqlite",
    "firebase",
    "supabase",
    "pandas",
    "numpy",
    "scikit-learn",
    "sklearn",
    "tensorflow",
    "pytorch",
    "keras",
    "opencv",
    "nlp",
    "machine learning",
    "deep learning",
    "data analysis",
    "etl",
    "power bi",
    "tableau",
    "excel",
    "figma",
    "jira",
    "agile",
    "scrum",
    "devops",
    "oop",
    "solid",
    "design patterns",
    "blockchain",
    "web3",
    "solidity",
    "wordpress",
    "shopify",
    "salesforce",
    "sap",
    "automation",
    "qa",
    "testing",
    "security",
    "cybersecurity",
    "networking",
    "tcp/ip",
    "wireshark",
    "postman",
    "swagger",
    "openapi",
    "kafka",
    "rabbitmq",
    "celery",
    "rabbitmq",
    "spark",
    "hadoop",
    "airflow",
    "dbt",
    "snowflake",
    "bigquery",
    "streamlit",
    "jupyter",
    "huggingface",
    "llm",
    "openai",
    "langchain",
    "vector database",
    "pinecone",
    "web scraping",
    "scrapy",
    "beautifulsoup",
    "requests",
    "http",
    "json",
    "xml",
    "yaml",
    "toml",
    "webpack",
    "vite",
    "babel",
    "sass",
    "tailwind",
    "bootstrap",
    "material ui",
    "redux",
    "zustand",
    "rxjs",
    "socket.io",
    "websockets",
    "mqtt",
    "iot",
    "embedded",
    "arduino",
    "raspberry pi",
    "cuda",
    "gpu",
    "vim",
    "vscode",
    "intellij",
    "eclipse",
    "xcode",
    "unity",
    "unreal",
    "blender",
    "maya",
    "photoshop",
    "illustrator",
    "ui/ux",
    "ux",
    "ui design",
    "technical writing",
    "documentation",
    "project management",
    "leadership",
    "communication",
    "teamwork",
    "problem solving",
)

# Boilerplate / soft skills that appear in almost every JD. Excluded from JD
# requirement mining, missing-skills, and keyword generation so they don't cause
# cross-domain false matches (a writer JD "matching" a developer resume).
SOFT_SKILLS: frozenset = frozenset({
    "communication", "teamwork", "leadership", "problem solving",
    "project management", "technical writing", "documentation", "agile", "scrum",
})

# Hard technical skills only — the signal that actually indicates role fit.
TECH_SKILLS: tuple = tuple(s for s in SKILLS if s not in SOFT_SKILLS)
